# 💝 Sponsor LeadMagic MCP Server

# GitHub Sponsors
github: LeadMagic

# Custom funding URLs
custom: ['https://leadmagic.io/sponsor', 'https://app.leadmagic.io/pricing']

# Support the development of LeadMagic MCP Server
# Your contributions help us maintain and improve this open-source project
# and provide better B2B data enrichment tools for the community. 